# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=10),
        ),
    ]
