# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
