# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20170210_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='shortname',
            field=models.CharField(default='undefined', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
