# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.School'),
            preserve_default=False,
        ),
    ]
