# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import food.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0015_auto_20170213_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lnglat', models.CharField(blank=True, max_length=50, validators=[food.models.lnglat_validator])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
