# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
        migrations.AddField(
            model_name='map',
            name='rest_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
