# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_auto_20170214_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='rest_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Restaurant'),
        ),
    ]
