# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Meal')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
