# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_mealcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
