# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_mealcomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='rest_name',
        ),
        migrations.RemoveField(
            model_name='map',
            name='school',
        ),
        migrations.RemoveField(
            model_name='map',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lnglat',
            field=models.CharField(blank=True, max_length=50, validators=[food.models.lnglat_validator]),
        ),
        migrations.AddField(
            model_name='school',
            name='center',
            field=models.CharField(blank=True, max_length=50, validators=[food.models.lnglat_validator]),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
